sudo: required
services:
    - docker

before_install:
    - docker build -t bashchap/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bashchap/docker-react npm run test

language: generic

deploy:
    provider: s3
    edge:
        branch: master
        access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-eu-west-1-159544763636"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"