FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .
# RUN chown -R node:node /app/node_modules
RUN chown node:node /app/node_modules
EXPOSE 80
CMD ["npm", "run", "start"]